version: "3.7"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: project
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: unless-stopped
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - 5001:8081

volumes:
    mongodb_data_container: